### ISSUE TITLE
Rough workflow to test converter

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/converters#1]
### Dotnet ≥ 7

install dotnet 7.0 (or check via dotnet --version)

### Have a converter-ready ARC Commander version

Until released, we need to locally build the developer version of ARC Commander, which can read from the converters repo.

1. Clone / pull ARC [Commander repo](https://github.com/nfdi4plants/arcCommander)
2. Switch to branch `arcIONetMigration`
3. run `dotnet run --project ./build/Build.fsproj`
4. find the ARC Commander executable in "src/ArcCommander/bin/Release/net7.0/arc"
5. copy paste the `<EXECUTABLEPATH>` (`~/path/to/ARCCommander-Repo/src/ArcCommander/bin/Release/net7.0/arc`)

### General command

- arc convert <CONVERTERNAME>
- options for <CONVERTERNAME> are
  - (currently one of two) converters available in https://github.com/nfdi4plants/converters/tree/main/converters (e.g. arc-convert-geo.fsx -> `arc convert geo`)
  - or a local absolute path to a .dll (e.g. `arc convert local/path/converterXYZ.dll`)

"EXECUTABLEPATH convert <CONVERTERNAME>"

### Get the working example arc

```bash
arc get -r https://git.nfdi4plants.org/weil/GeoSampleArc
```

Navigate to and execute converter tests in `GeoSampleArc`

### Test "working" converters

Run `arc convert geo` and `arc convert invenio` 

### Test local building

1. Install FSharpPacker via `dotnet tool install --global FSharpPacker`
1. Download .fsx examples from https://github.com/nfdi4plants/converters/tree/main/converters
1. pack to dll via `fspack converters/arc-convert-invenio.fsx -o pkg/invenio -f net7.0`
1. Test with locally packed dll: `arc convert pkg/invenio/arc-convert-invenio.dll`

### Build and test a minimal converter

1. Write a minimal .fsx (few rows and columns)
2. Pack to .dll 
3. test "conversion"

### Test publishing to converters repo

1. fork converters repo
1. add fsx to converters subdir
1. add pack commands to github workflow
1. PR

**Comment by Brilator** [comment]
MacOS
- `dotnet tool install --global FSharpPacker` worked ✅

**Comment by Brilator** [comment]
# converter test protocol

- path to ARC commander: ~/github/nfdi4plants/arcCommander/src/ArcCommander/bin/Release/net7.0/arc

## Online dll built

`~/github/nfdi4plants/arcCommander/src/ArcCommander/bin/Release/net7.0/arc convert geo`

Error:

```bash
Start processing command with the arguments:
        AssayIdentifier:Field ""
        StudyIdentifier:Field ""
        Target:Field "geo"
 
Start Arc Convert 
arc-convert-geo 
Fetch converter dll 
Load ARC 
Run conversion 
Done processing command. 
ERROR: System.TypeLoadException: Could not load type 'ISADotNet.QueryModel.Study' from assembly 'ISADotNet.QueryModel, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'. System.TypeLoadException: Could not load type 'ISADotNet.QueryModel.Study' from assembly 'ISADotNet.QueryModel, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at arc-convert-geo.create@15.Invoke(QInvestigation i, QStudy s, QAssay a)
   at ArcCommander.ArcConversion.handleXLSX[a](QInvestigation i, QStudy s, QAssay a, String arcDir, a converterName, ARCconverter f) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/ArcConversion.fs:line 124
   at ArcCommander.APIs.ArcAPI.convert(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/APIs/ArcAPI.fs:line 188
   at ArcCommander.Program.handleCommand@218-2.Invoke(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs)
   at ArcCommander.Program.processCommand[a,T](ArcConfiguration arcConfiguration, FSharpFunc`2 commandF, ParseResults`1 r) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 52
   at ArcCommander.Program.handleCommand(ArcConfiguration arcConfiguration, ArcCommand command) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 218
   at ArcCommander.Program.main(String[] argv) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 277
```

## local built

### build converter from fsx

```bash
cd ~/github/nfdi4plants/converters/
fspack converters/arc-convert-geo.fsx -o pkg/geo -f net7.0
```

Warnings:

```bash
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 7.0.300-beta.23114.3 to 7.0.0. Reference the package directly from the project to select a different version. 
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605:  arc-convert-geo -> arcIO.NET 0.1.0-preview.6 -> FSharp.Core (>= 7.0.300-beta.23114.3) 
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605:  arc-convert-geo -> FSharp.Core (>= 7.0.0)
  Restored /var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj (in 4.69 sec).
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 7.0.300-beta.23114.3 to 7.0.0. Reference the package directly from the project to select a different version. 
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605:  arc-convert-geo -> arcIO.NET 0.1.0-preview.6 -> FSharp.Core (>= 7.0.300-beta.23114.3) 
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj : warning NU1605:  arc-convert-geo -> FSharp.Core (>= 7.0.0)
/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpJVrmAz.tmp.fs(300,2): warning FS0988: Main module of program is empty: nothing will happen when it is run [/var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/tmpYGjxRr.tmp.fsproj]
  tmpYGjxRr.tmp -> /var/folders/yb/b_h992r92dsdk93c6vpqh_b40000gp/T/bin/Release/net7.0/osx-x64/arc-convert-geo.dll
  tmpYGjxRr.tmp -> $HOME/github/nfdi4plants/converters/pkg/geo/
```


- path to geo converter: $HOME/github/nfdi4plants/converters/pkg/geo/arc-convert-geo.dll


### build converter from fsx

```bash
~/github/nfdi4plants/arcCommander/src/ArcCommander/bin/Release/net7.0/arc --help
```

```bash
cd ~/gitlab_dataplant/GeoSampleArc
~/github/nfdi4plants/arcCommander/src/ArcCommander/bin/Release/net7.0/arc convert ~/github/nfdi4plants/converters/pkg/geo/arc-convert-geo.dll
```

Error: 

```bash
ERROR: System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection. System.Collections.Generic.KeyNotFoundException: An index satisfying the predicate was not found in the collection.
   at Microsoft.FSharp.Collections.SeqModule.Find[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 811
   at ArcCommander.ArcConversion.getDll(String repoOwner, String repoName, String dllname) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/ArcConversion.fs:line 52
   at ArcCommander.APIs.ArcAPI.convert(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/APIs/ArcAPI.fs:line 171
   at ArcCommander.Program.handleCommand@218-2.Invoke(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs)
   at ArcCommander.Program.processCommand[a,T](ArcConfiguration arcConfiguration, FSharpFunc`2 commandF, ParseResults`1 r) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 52
   at ArcCommander.Program.handleCommand(ArcConfiguration arcConfiguration, ArcCommand command) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 218
   at ArcCommander.Program.main(String[] argv) in /Users/dominikbrilhaus/github/nfdi4plants/arcCommander/src/ArcCommander/Program.fs:line 277
```
